# Generated by Django 5.0.1 on 2025-02-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_mobile_no'),
    ]

    operations = [
    ]
