# Generated by Django 5.0.1 on 2025-03-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_id_admin_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
