# Generated by Django 5.0.1 on 2025-02-20 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('director', models.CharField(max_length=300)),
                ('cast', models.CharField(max_length=300)),
                ('release_date', models.DateField()),
                ('description', models.TextField(max_length=5000)),
                ('rating', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('genre', models.CharField(blank=True, max_length=300, null=True)),
                ('gross_collection', models.BigIntegerField(blank=True, null=True)),
                ('production', models.CharField(blank=True, max_length=300, null=True)),
                ('trailer_id', models.CharField(blank=True, max_length=300, null=True)),
                ('streaming_on', models.CharField(blank=True, max_length=300, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('rating', models.FloatField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('favorite_genre', models.CharField(blank=True, choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Romance', 'Romance')], max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('reviews_count', models.IntegerField(default=0)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watched_movies', models.ManyToManyField(blank=True, to='main.movie')),
            ],
        ),
    ]
